using System.Windows.Media;

namespace Athlon.Agent.App.Themes;

internal static class EditorSyntaxColorMaps
{
    public static IReadOnlySet<string> BoldTokenNames { get; } = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "Keywords",
        "Visibility",
        "ValueTypeKeywords",
        "ReferenceTypeKeywords",
        "MethodCall",
        "ThisOrBaseReference",
        "NullOrValueKeywords",
        "GotoKeywords",
        "ContextKeywords",
        "ExceptionKeywords",
        "CheckedKeyword",
        "OperatorKeywords",
        "ParameterModifiers",
        "NamespaceKeywords",
        "TypeKeywords",
        "SemanticKeywords",
        "TrueFalse",
        "Heading",
        "HtmlTag",
        "ScriptTag",
        "JavaScriptTag",
    };

    public static IReadOnlyDictionary<string, Color> CreateDark() =>
        new Dictionary<string, Color>(StringComparer.OrdinalIgnoreCase)
        {
            ["Comment"] = C("#6A9955"),
            ["Preprocessor"] = C("#9B9B9B"),
            ["XmlDoc/DocComment"] = C("#608B4E"),
            ["String"] = C("#CE9178"),
            ["Char"] = C("#CE9178"),
            ["Character"] = C("#CE9178"),
            ["StringInterpolation"] = C("#CE9178"),
            ["Regex"] = C("#D16969"),
            ["NumberLiteral"] = C("#B5CEA8"),
            ["Digits"] = C("#B5CEA8"),
            ["Number"] = C("#B5CEA8"),
            ["Bool"] = C("#569CD6"),
            ["TrueFalse"] = C("#569CD6"),
            ["Null"] = C("#569CD6"),
            ["JavaScriptLiterals"] = C("#569CD6"),
            ["Keywords"] = C("#569CD6"),
            ["Visibility"] = C("#569CD6"),
            ["Modifiers"] = C("#569CD6"),
            ["GotoKeywords"] = C("#569CD6"),
            ["ContextKeywords"] = C("#569CD6"),
            ["ExceptionKeywords"] = C("#569CD6"),
            ["CheckedKeyword"] = C("#569CD6"),
            ["UnsafeKeywords"] = C("#569CD6"),
            ["OperatorKeywords"] = C("#569CD6"),
            ["ParameterModifiers"] = C("#569CD6"),
            ["NamespaceKeywords"] = C("#569CD6"),
            ["GetSetAddRemove"] = C("#569CD6"),
            ["NullOrValueKeywords"] = C("#569CD6"),
            ["SemanticKeywords"] = C("#569CD6"),
            ["ThisOrBaseReference"] = C("#569CD6"),
            ["TypeKeywords"] = C("#569CD6"),
            ["ValueTypeKeywords"] = C("#569CD6"),
            ["ReferenceTypeKeywords"] = C("#569CD6"),
            ["JavaScriptKeyWords"] = C("#569CD6"),
            ["JavaScriptIntrinsics"] = C("#569CD6"),
            ["ReferenceTypes"] = C("#4EC9B0"),
            ["MethodCall"] = C("#DCDCAA"),
            ["JavaScriptGlobalFunctions"] = C("#DCDCAA"),
            ["FieldName"] = C("#9CDCFE"),
            ["Attributes"] = C("#9CDCFE"),
            ["Property"] = C("#9CDCFE"),
            ["UnknownAttribute"] = C("#9CDCFE"),
            ["HtmlTag"] = C("#569CD6"),
            ["Tags"] = C("#808080"),
            ["ScriptTag"] = C("#569CD6"),
            ["JavaScriptTag"] = C("#569CD6"),
            ["JScriptTag"] = C("#569CD6"),
            ["VBScriptTag"] = C("#569CD6"),
            ["UnknownScriptTag"] = C("#569CD6"),
            ["EntityReference"] = C("#569CD6"),
            ["Entities"] = C("#569CD6"),
            ["Assignment"] = C("#D4D4D4"),
            ["Slash"] = C("#808080"),
            ["Selector"] = C("#D7BA7D"),
            ["Class"] = C("#D7BA7D"),
            ["Value"] = C("#CE9178"),
            ["CurlyBraces"] = C("#D4D4D4"),
            ["Colon"] = C("#D4D4D4"),
            ["Heading"] = C("#569CD6"),
            ["Emphasis"] = C("#D4D4D4"),
            ["StrongEmphasis"] = C("#D4D4D4"),
            ["Code"] = C("#CE9178"),
            ["BlockQuote"] = C("#6A9955"),
            ["Link"] = C("#4EC9B0"),
            ["Image"] = C("#4EC9B0"),
            ["LineBreak"] = C("#D4D4D4"),
            ["Punctuation"] = C("#D4D4D4"),
        };

    private const string LightKeywordBlue = "#1A56DB";

    public static IReadOnlyDictionary<string, Color> CreateLight() =>
        new Dictionary<string, Color>(StringComparer.OrdinalIgnoreCase)
        {
            ["Comment"] = C("#008000"),
            ["Preprocessor"] = C("#808080"),
            ["XmlDoc/DocComment"] = C("#008000"),
            ["String"] = C("#A31515"),
            ["Char"] = C("#A31515"),
            ["Character"] = C("#A31515"),
            ["StringInterpolation"] = C("#A31515"),
            ["Regex"] = C("#811F3F"),
            ["NumberLiteral"] = C("#098658"),
            ["Digits"] = C("#098658"),
            ["Number"] = C("#098658"),
            ["Bool"] = C(LightKeywordBlue),
            ["TrueFalse"] = C(LightKeywordBlue),
            ["Null"] = C(LightKeywordBlue),
            ["JavaScriptLiterals"] = C(LightKeywordBlue),
            ["Keywords"] = C(LightKeywordBlue),
            ["Visibility"] = C(LightKeywordBlue),
            ["Modifiers"] = C(LightKeywordBlue),
            ["GotoKeywords"] = C(LightKeywordBlue),
            ["ContextKeywords"] = C(LightKeywordBlue),
            ["ExceptionKeywords"] = C(LightKeywordBlue),
            ["CheckedKeyword"] = C(LightKeywordBlue),
            ["UnsafeKeywords"] = C(LightKeywordBlue),
            ["OperatorKeywords"] = C(LightKeywordBlue),
            ["ParameterModifiers"] = C(LightKeywordBlue),
            ["NamespaceKeywords"] = C(LightKeywordBlue),
            ["GetSetAddRemove"] = C(LightKeywordBlue),
            ["NullOrValueKeywords"] = C(LightKeywordBlue),
            ["SemanticKeywords"] = C(LightKeywordBlue),
            ["ThisOrBaseReference"] = C(LightKeywordBlue),
            ["TypeKeywords"] = C(LightKeywordBlue),
            ["ValueTypeKeywords"] = C(LightKeywordBlue),
            ["ReferenceTypeKeywords"] = C("#2B91AF"),
            ["JavaScriptKeyWords"] = C(LightKeywordBlue),
            ["JavaScriptIntrinsics"] = C(LightKeywordBlue),
            ["ReferenceTypes"] = C("#2B91AF"),
            ["MethodCall"] = C("#795E26"),
            ["JavaScriptGlobalFunctions"] = C("#795E26"),
            ["FieldName"] = C("#001080"),
            ["Attributes"] = C("#001080"),
            ["Property"] = C("#001080"),
            ["UnknownAttribute"] = C("#001080"),
            ["HtmlTag"] = C("#800000"),
            ["Tags"] = C("#800000"),
            ["ScriptTag"] = C("#800000"),
            ["JavaScriptTag"] = C("#800000"),
            ["JScriptTag"] = C("#800000"),
            ["VBScriptTag"] = C("#800000"),
            ["UnknownScriptTag"] = C("#800000"),
            ["EntityReference"] = C("#800000"),
            ["Entities"] = C("#800000"),
            ["Assignment"] = C("#000000"),
            ["Slash"] = C("#808080"),
            ["Selector"] = C("#800000"),
            ["Class"] = C("#800000"),
            ["Value"] = C("#A31515"),
            ["CurlyBraces"] = C("#000000"),
            ["Colon"] = C("#000000"),
            ["Heading"] = C("#800000"),
            ["Emphasis"] = C("#000000"),
            ["StrongEmphasis"] = C("#000000"),
            ["Code"] = C("#A31515"),
            ["BlockQuote"] = C("#008000"),
            ["Link"] = C("#4F46E5"),
            ["Image"] = C("#4F46E5"),
            ["LineBreak"] = C("#000000"),
            ["Punctuation"] = C("#000000"),
        };

    private static Color C(string hex) => AppThemeColor.FromHex(hex);
}
